Fix mertic service
qiwi/nestjs-enterprise pull request #111
Opened 2023-10-20 11:59 UTC by ZhuzhginNA

Fixes [#id]

## Changes

- [ ] New code is covered by tests
- [ ] All the changes are mentioned in docs (readme.md)

2023-10-24 07:15 UTC, Demian222 approved these changes

2023-10-24 09:02 UTC, oljekechoro requested changes

2023-10-24 09:02 UTC, oljekechoro commented on packages/metric/package.json
> +  "types": "./target/esm/index.d.ts",
types should be only in publishConfig

2023-10-24 09:02 UTC, oljekechoro commented on packages/metric/package.json
> +  "files": [
files should be only in publishConfig

2023-10-24 09:03 UTC, antongolub commented on packages/metric/qiwi-nestjs-enterprise-metric-1.6.1.tgz
?

2023-10-25 09:57 UTC, oljekechoro requested changes

2023-10-25 09:57 UTC, oljekechoro commented on packages/metric/src/main/ts/metric.module.ts
>        inject: ['IGraphiteService', 'IConfigService'],
Do not forget

2023-10-25 09:57 UTC, oljekechoro commented on packages/metric/src/main/ts/metric.module.ts
>            inject: ['IGraphiteService'],
ILogger is missing too

2023-10-26 14:45 UTC, oljekechoro approved these changes

2023-10-26 14:47 UTC, merged