feat(common): add graphite decorator
qiwi/nestjs-enterprise pull request #72
Opened 2022-12-08 20:15 UTC by pismenskiy

2022-12-08 20:21 UTC, oljekechoro requested changes

2022-12-08 20:21 UTC, oljekechoro commented on packages/common/src/main/ts/graphit-metric/graphite.service.ts
> +    // @ts-ignore
без не получится?

2022-12-08 20:22 UTC, antongolub requested changes

2022-12-08 20:22 UTC, antongolub commented on packages/common/src/main/ts/graphit-metric/graphite.service.ts
> +      GraphiteLogger.applicationName = applicationName || env.APP_NAME
wtf?

2022-12-08 20:22 UTC, antongolub commented on packages/common/src/main/ts/graphit-metric/gm-rpm.decorator.ts
> +export const GmRpmDecorator = constructDecorator(
`@Metered`, not `@Rpm`

2022-12-09 12:04 UTC, oljekechoro approved these changes

2022-12-09 12:05 UTC, antongolub requested changes

2022-12-09 12:05 UTC, antongolub commented on packages/common/src/main/ts/graphit-metric/graphite.service.ts
> +    return `$type.app.$cluster.${this.applicationName}.$host.${this.environment}-${this.datacenter}-${this.podId}.$metric.${metricName}`
no

2022-12-23 10:23 UTC, oljekechoro requested changes

2022-12-23 10:23 UTC, oljekechoro commented on packages/common/tsconfig.json
> +    "tsBuildInfoFile": "./buildcache/.tsbuildinfo",
trailing slash в json?

2022-12-23 10:23 UTC, oljekechoro commented on packages/metric/src/main/ts/metric.service.ts
> +    if (this.collectionTimer.lenght) return
length

2022-12-23 10:23 UTC, oljekechoro commented on packages/metric/src/main/ts/graphite.service.ts
> +    return new Promise((resolve, reject) => {
Promise<void>

2022-12-23 11:11 UTC, oljekechoro approved these changes

2022-12-23 11:18 UTC, antongolub requested changes

2022-12-23 11:18 UTC, antongolub commented on packages/metric/package.json
> +    "esm": "^3.2.25",
@qiwi/esm

2022-12-23 11:18 UTC, antongolub commented on packages/metric/package.json
> +  "source": "target/ts/index.ts",
rm. This is for sourcemaps

2022-12-23 11:18 UTC, antongolub commented on packages/metric/package.json
> +    "logger"
metrics

2022-12-23 11:18 UTC, antongolub commented on packages/metric/src/main/ts/decorators/error.decorator.ts
> +      return target.apply(this, args).catch((e: any) => {
This may be sync

2022-12-23 11:48 UTC, antongolub requested changes

2022-12-23 11:48 UTC, antongolub commented on packages/metric/src/main/ts/decorators/error.decorator.ts
>      const injectMetric = Inject('IMetricService')
```js
const isPromise = (value) => value instanceof Promise || (typeof value?.then === 'function' && typeof value?.catch === 'faunction')
const onError = (e) => {...}
...

try {
  const res = target.apply(...)
  
  if (isPromise(res)) {
      return res.catch(onError)
  }
  
} catch (e) {
   onError(e)
}
```

2022-12-23 12:11 UTC, antongolub approved these changes

2023-01-17 12:05 UTC, merged