docs: update readme, add jsdoc annotations, fix interfaces, formatting
qiwi/nestjs-enterprise pull request #95
Opened 2023-09-15 15:25 UTC by Demian222

2023-09-15 15:38 UTC, antongolub requested changes

2023-09-15 15:38 UTC, antongolub commented on packages/connection-provider/src/main/ts/interfaces.ts
> -export type IConnectionParams = {
1. Types refactoring will bring a breaking change
2. Consul module _implements_ conn provider contract, so the types should stay here or be moved upper to the common module.

2023-09-18 12:22 UTC, oljekechoro commented on packages/logger/src/main/ts/app.pipe.ts
> + * @return {ILogEntry} assign logger entry meta and params (name, versions, host)
assigned, imho?

2023-09-18 12:25 UTC, oljekechoro commented on packages/logger/src/main/ts/winston.ts
> + * @param {TWinstonEntry} entry - logEntry with format winston
winston format

2023-09-18 12:26 UTC, oljekechoro commented on packages/logger/src/main/ts/winston.ts
> + * @return - logEntry with format kibana
kibana format

2023-09-18 12:26 UTC, oljekechoro commented on packages/consul/src/main/ts/consul.service.ts
> +   * @return Return value by key
value by key

2023-09-18 12:26 UTC, oljekechoro commented on packages/consul/src/main/ts/consul.service.ts
> +   * @return Return host and port to connection
host and port for connection

2023-09-18 12:27 UTC, oljekechoro requested changes
small typos

2023-09-18 18:53 UTC, oljekechoro commented on package.json
> +    "build": "yarn clean && yarn prebuild && yarn workspaces foreach --topological-dev run build",
-p?

2023-09-18 18:56 UTC, oljekechoro commented on packages/connection-provider/src/main/ts/connection-provider.service.ts
> +    private consul: IAbstractConsulService,
IDiscoverable?

2023-09-19 09:31 UTC, oljekechoro commented on packages/thrift/src/main/ts/thrift.client.ts
> +          typeof serviceProfile === 'string' ? serviceProfile : ''
а тут типа при ошибке, если не string, будет `Bad connections params - `?

2023-09-19 11:06 UTC, oljekechoro approved these changes

2023-09-19 11:14 UTC, merged